"""Add remittance resolved status

Revision ID: d9eccfebc12e
Revises: a5423a0b87b9
Create Date: 2026-09-01 15:18:05.398494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9eccfebc12e'
down_revision = 'a5423a0b87b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remittances', schema=None) as batch_op:
        batch_op.add_column(
        sa.Column(
        'resolved',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false(),
    )
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remittances', schema=None) as batch_op:
        batch_op.drop_column('resolved')

    # ### end Alembic commands ###
