"""remove driver_id from remittances, derive via driver_assignments

Revision ID: f18f11ffe40b
Revises: 5e1802c7fdd7
Create Date: 2026-08-27 22:13:03.079985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18f11ffe40b'
down_revision = '5e1802c7fdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remittances', schema=None) as batch_op:
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remittances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['driver_id'], ['id'])

    # ### end Alembic commands ###
